### ISSUE TITLE
Sublime Text link is broken

### ISSUE THREAD

**Issue by danielpmaloney** [okcoders/ok-coders-january-2017-front-end#1]
Sublime text link in the mac getting started instructions no longer works. Updated link: https://www.sublimetext.com/

**Comment by jnasante** [comment]
Hmm, it's odd that the link didn't work for you, because it was there as: [http://www.sublimetext.com/](http://www.sublimetext.com/). However, I've updated it to _https_ in case that was why it wasn't working for you. Thanks!
